name: cd

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd one-pager-maker
          npm install
          npm install -g firebase-tools
          npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          working-directory: one-pager-maker
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ONE_PAGER_MAKER }}"
          channelId: live
          projectId: one-pager-maker

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: bun run e2e:all
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure() || cancelled()
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
