name: Staging Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write
  actions: write
  checks: write
  statuses: write

jobs:
  deployment:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      run:
        working-directory: one-pager-maker
    concurrency: staging
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: cache-node-modules
        uses: actions/cache@v3
        id: cache-bun
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-cache-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-bun-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: bun install
        if: ${{ steps.cache-bun.outputs.cache-hit != 'true' }}
        run: bun i
      - name: install firebase-tools
        run: bun i -g firebase-tools
      - name: Rewrite .env.staging file
        shell: bash
        run: |
          cat <<EOF > .env.staging
          VITE_API_KEY=${{ secrets.STAGING_VITE_API_KEY }}
          VITE_AUTH_DOMAIN=${{ secrets.STAGING_VITE_AUTH_DOMAIN }}
          VITE_PROJECT_ID=${{ secrets.STAGING_VITE_PROJECT_ID }}
          VITE_STORAGE_BUCKET=${{ secrets.STAGING_VITE_STORAGE_BUCKET }}
          VITE_MESSAGING_SENDER_ID=${{ secrets.STAGING_VITE_MESSAGING_SENDER_ID }}
          VITE_APP_ID=${{ secrets.STAGING_VITE_APP_ID }}
          VITE_MEASUREMENT_ID=${{ secrets.STAGING_VITE_MEASUREMENT_ID }}
          EOF
      - name: build
        run: bun run build:staging
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.STAGING_FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: one-pager-maker-staging-id
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: bun run e2e:all
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure() || cancelled()
        with:
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
