name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
      - EnvironmentSetting #後から外す
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: oven-sh/setup-bun@v1
      - name: lint and test
        run: |
          cd one-page-maker
          bun install
          bun run lint
          bun run test
      - run: |
          cd one-page-maker
          bun run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAMPLE_APP_12BF5 }}"
          channelId: live
          projectId: one-pager-maker
