name: ci

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: oven-sh/setup-bun@v1
      # TODO:cached
      - name: install
        run: |
          cd one-pager-maker
          bun install
          bun install -g firebase-tools
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          working-directory: one-pager-maker
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ONE_PAGER_MAKER }}"
          channelId: live
          projectId: one-pager-maker
      # TODO:cached
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: bun run e2e:all
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
