name: schedule_reminder

on:
  schedule:
    # Thursday 22:00 JST
    - cron: "* 13 * * 5"

jobs:
  send_reminder:
    runs-on: ubuntu-latest
    steps:
      - name: discord reminder
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Auto Reminder
          text: Regular meeting tomorrow at 10pm.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
