name: schedule_reminder

on:
  pull_request:
    branches:
      - main

# on:
#   schedule:
#     # Friday 20:00 + Î± JST
#     - cron: "0 11 * * 5"

jobs:
  send_reminder:
    runs-on: ubuntu-latest
    steps:
      - name: discord reminder
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: Github Actions Reminder
          text: It starts in an hour! @!1029901876533133423 @!482924039191396353 @!257981616004136961
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
