name: schedule_reminder

on:
  schedule:
    # Friday 21:00 JST
    - cron: "0 12 * * 5"

jobs:
  send_reminder:
    runs-on: ubuntu-latest
    steps:
      - name: discord reminder
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: Github Actions Reminder
          text: @takashitanaka_kccs @binnmti @harineko0  It starts in an hour.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
